import AuthContextProvider from "@/contexts/auth/AuthContextProvider";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[1440px] m-auto">
        <AuthContextProvider>
          <Header />
          <div className="mt-2">{children}</div>
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
